export default {
    domains: {
        'nytimes.com': ['smid', 'smtyp'],
        'youtube.com': ['app', 'feature'],
        'thehill.com': ['userid'],
        'twitter.com': ['s'],
        'reuters.com': ['feedtype', 'feedname'],
        'zeit.de': ['wt_zmc'],
        'washingtonpost.com': ['noredirect'],
        'dw.com': ['maca'],
    },
    default: [
        'utm_source',
        'utm_medium',
        'utm_term',
        'utm_campaign',
        'utm_content',
        'utm_name',
        'utm_cid',
        'utm_reader',
        'utm_viz_id',
        'utm_pubreferrer',
        'utm_swu',
        'igshid',
        'fbclid',
        'gclid',
        'ocid',
        'ncid',
        'bcid',
        'bhid',
        'recid',
        'icid',
        'ito',
        'wkey',
        'wemail',
        'wtmc',
        'wt_mc',
        'nr_email_referer',
        'ref',
        'spm',
        'ftag',
        'recip',
        'ktm_source',
        'mkt_toc',
        'mkt_tok',
        'mc_cid',
        'mc_eid',
        'ns_source',
        'ns_mchannel',
        'ns_campaign',
        'ns_linkname',
        'ns_fee',
        'sr_share',
        'vero_conv',
        'vero_id',
        '_hsenc',
        '_hsmi',
        'hsctatracking',
        '__twitter_impression',
        'newsletterad',
    ],
};
